### ISSUE TITLE
ToDo: Add conversion of a group of datasets

### ISSUE THREAD

**Issue by willirath** [willirath/nemo_cf#8]
- [ ] After #7 is fixed
- [ ] Add conversion of many datasets 
- [ ] Add cli tool wrapper for conversion.
